import { MonitorPlay, Ship, Utensils, Waves } from "lucide-react";

export const BFeatures = [
  {
    id: 1,
    label: "Features",
    value: "features",
    icon: (
      <MonitorPlay className="size-12 md:size-14 lg:size-16 text-sky-800" />
    ),
    items: [
      "Amplifier",
      "Bluetooth",
      "Speaker",
      "Karaoke",
      "Music",
      "Instrument",
      "TV",
      "Audio and Video Entertainment",
      "Fishing rope",
      "Floaties",
      "Spa/Massage",
      "Telescope",
      "Yoga Mat",
    ],
  },
  {
    id: 2,
    label: "Water Activities",
    value: "water_activities",
    icon: <Waves className="size-12 md:size-14 lg:size-16 text-sky-800" />,
    items: [
      "Kayaking",
      "Canoe",
      "Paddle board",
      "Wake board",
      "Banana Boat",
      "Air Slide",
      "Snorkeling",
      "Diving",
      "Snorkeling and Diving Equipments",
    ],
  },
  {
    id: 3,
    label: "Food and Drinks",
    value: "food_and_drinks",
    icon: <Utensils className="size-12 md:size-14 lg:size-16 text-sky-800" />,
    items: [
      "Beach BBQ",
      "Beachside dining",
      "Buffet Style",
      "Beer available",
      "Cocktail",
      "Fine Cuisine",
      "Fine Wines Selection",
      "Soft Drinks",
      "Local Food",
      "Snacks All Day",
      "Set Menu Dinner",
      "Vegetarian Options",
      "Wine",
    ],
  },
  {
    id: 4,
    label: "Facilities",
    value: "facilities",
    icon: <Ship className="size-12 md:size-14 lg:size-16 text-sky-800" />,
    items: [
      "Air conditioned",
      "Bar",
      "Camera Station",
      "Charging Stations",
      "Dive Deck",
      "En-Suite Bathrooms",
      "Family Cabins",
      "Laundry Service",
      "Leisure Deck",
      "Non-Diver Friendly",
      "Non-Smoking Rooms",
      "Outdoor Dining",
      "Outside Showers",
      "Rinse Hose",
      "Sun Deck",
      "Sunbathing Chair",
      "Warm Water Showers",
    ],
  },
];
